# Generated by Django 4.0.3 on 2022-04-12 13:53

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('event_date', models.DateTimeField(verbose_name='event date')),
                ('descr_text', models.CharField(max_length=5000, verbose_name='description')),
                ('city_text', models.CharField(max_length=255)),
                ('location_map', location_field.models.plain.PlainLocationField(max_length=63)),
                ('type_event', models.CharField(choices=[('C', 'Competicao'), ('W', 'Workshop'), ('P', 'Palestra'), ('T', 'Tradicional')], max_length=40)),
                ('part_number', models.IntegerField(default=0)),
                ('banner', models.ImageField(upload_to='banners')),
            ],
        ),
    ]
