# Generated by Django 4.0.3 on 2022-05-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descr_text',
            field=models.TextField(max_length=5000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
