# Generated by Django 4.0.3 on 2022-05-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_evento_descr_text_alter_evento_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners'),
        ),
    ]
